// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxPE-l1bh-kaP8MufqKbbjng5s-10eKg',
    appId: '1:186090767131:web:e6777432229963e1b789be',
    messagingSenderId: '186090767131',
    projectId: 'dormfix-6719d',
    authDomain: 'dormfix-6719d.firebaseapp.com',
    storageBucket: 'dormfix-6719d.firebasestorage.app',
    measurementId: 'G-TN4NP0P49X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQQPrXYmSvrsJtMcqs0PeSJA6dSWD8YRU',
    appId: '1:186090767131:android:81f856dc676d4ac6b789be',
    messagingSenderId: '186090767131',
    projectId: 'dormfix-6719d',
    storageBucket: 'dormfix-6719d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJ_39ZSnt-AgW0GoyxoMYPYr5-nMaLc8',
    appId: '1:186090767131:ios:d622cf18d1c496cab789be',
    messagingSenderId: '186090767131',
    projectId: 'dormfix-6719d',
    storageBucket: 'dormfix-6719d.firebasestorage.app',
    iosBundleId: 'com.example.dormfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJ_39ZSnt-AgW0GoyxoMYPYr5-nMaLc8',
    appId: '1:186090767131:ios:d622cf18d1c496cab789be',
    messagingSenderId: '186090767131',
    projectId: 'dormfix-6719d',
    storageBucket: 'dormfix-6719d.firebasestorage.app',
    iosBundleId: 'com.example.dormfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxxPE-l1bh-kaP8MufqKbbjng5s-10eKg',
    appId: '1:186090767131:web:fd5e13c21f757ac9b789be',
    messagingSenderId: '186090767131',
    projectId: 'dormfix-6719d',
    authDomain: 'dormfix-6719d.firebaseapp.com',
    storageBucket: 'dormfix-6719d.firebasestorage.app',
    measurementId: 'G-QTQBVN09X9',
  );
}
